extends SceneTree

func _initialize() -> void:
	call_deferred("_run")

func _run() -> void:
	var scene := load("res://scenes/main.tscn")
	var game: Variant = scene.instantiate()
	root.add_child(game)
	await process_frame
	game.start_game("English", 12345)
	if DisplayServer.get_name() != "headless": assert(Input.mouse_mode == game._gameplay_mouse_mode())
	assert(game.map_seed == 12345)
	var terrain_map: RtsWorldMap = game.world_map
	assert(terrain_map.cells.has(RtsWorldMap.Terrain.WATER), "map should contain water")
	assert(terrain_map.cells.has(RtsWorldMap.Terrain.MOUNTAIN), "map should contain mountains")
	assert(terrain_map.plants.size() > 100, "map should contain plant groups")
	var deer_count := 0
	for spec in terrain_map.resource_specs:
		if spec["appearance"] == "deer": deer_count += 1
	assert(deer_count >= 12, "map should contain harvestable deer herds")
	var same_seed_map := RtsWorldMap.new()
	same_seed_map.generate(12345, game.world_size)
	assert(same_seed_map.cells == terrain_map.cells and same_seed_map.resource_specs == terrain_map.resource_specs, "map generation should be reproducible")
	same_seed_map.free()
	var corridor := terrain_map.path_between(terrain_map.spawn_positions()[0], terrain_map.spawn_positions()[1])
	assert(not corridor.is_empty(), "both bases should be connected")
	for waypoint in corridor: assert(terrain_map.is_walkable(waypoint))
	var water_point: Vector2 = game._scaled_point(Vector2(800, 1220))
	assert(not terrain_map.is_walkable(water_point))
	assert(not game.can_place("house", water_point), "water should block construction")
	assert(game.weather.rain_active, "a new map should start with rain")
	game.weather.weather_remaining = 0.01
	game.weather._process(0.02)
	assert(not game.weather.rain_active, "rain should give way to clear weather")
	assert(game.units.size() == 12 and game.units.filter(func(unit: RtsUnit) -> bool: return unit.kind == "villager").size() == 10, "both civilizations should have starting villagers and scouts")
	assert(game.buildings.size() == 2, "both civilizations should have town centers")
	assert(game.population_cap(0) == 10)
	var escape := InputEventKey.new()
	escape.keycode = KEY_ESCAPE
	escape.pressed = true
	game._input(escape)
	assert(game.paused and game.pause_overlay.visible)
	assert(Input.mouse_mode == Input.MOUSE_MODE_VISIBLE)
	assert(not game.cursor.visible)
	var frozen_position: Vector2 = game.units[0].position
	game.units[0]._process(1.0)
	assert(game.units[0].position == frozen_position)
	game._input(escape)
	assert(not game.paused and not game.pause_overlay.visible)
	if DisplayServer.get_name() != "headless": assert(Input.mouse_mode == game._gameplay_mouse_mode())
	assert(game.cursor.visible)
	assert(game._edge_pan_direction(Vector2(640, 360), Vector2(1280, 720)) == Vector2.ZERO)
	assert(game._edge_pan_direction(Vector2(2, 360), Vector2(1280, 720)) == Vector2.LEFT)
	assert(game._edge_pan_direction(Vector2(1278, 718), Vector2(1280, 720)) == Vector2.ZERO, "hovering the bottom HUD should suppress edge scrolling")
	assert(game._edge_pan_direction(Vector2(-2, 360), Vector2(1280, 720)) == Vector2.LEFT)
	assert(game._edge_pan_direction(Vector2(1280, 720), Vector2(1280, 720)) == Vector2.ZERO, "clamped corner coordinates should respect the HUD")
	assert(game._edge_pan_direction(Vector2(1282, 360), Vector2(1280, 720)) == Vector2.RIGHT)
	game.global_queue_panel.show()
	assert(game._selection_point_over_hud(game.global_queue_panel.get_global_rect().get_center()), "native selection must not start behind the global queue")
	game.global_queue_panel.hide()
	game._begin_selection_candidate(Vector2(100, 100))
	assert(game.selection_drag_phase == game.SelectionDragPhase.CANDIDATE)
	assert(game.selection_drag_overlay.tracking and game.selection_drag_overlay.visible and game.selection_drag_overlay.anchor.visible, "press feedback should be immediate")
	game._update_selection_drag(Vector2(102, 100))
	assert(game.selection_drag_overlay.active and game.selection_drag_overlay.visible, "the first small movement should show the rectangle")
	assert(not game._selection_drag_active(), "visual feedback must not change click semantics")
	game._update_selection_drag(Vector2(113, 100))
	assert(game.selection_drag_phase == game.SelectionDragPhase.ACTIVE)
	assert(game._selection_drag_active(), "selection rectangle should activate after the drag threshold")
	assert(game.selection_drag_overlay != null, "the selection overlay should be available")
	var drag_motion := InputEventMouseMotion.new()
	drag_motion.position = Vector2(124, 100)
	game._update_selection_drag(drag_motion.position)
	assert(game.drag_current_screen == drag_motion.position, "active drags should keep receiving motion before the HUD")
	assert(game.selection_drag_overlay.active and game.selection_drag_overlay.visible)
	assert(game.selection_drag_overlay.screen_rect() == Rect2(Vector2(100, 100), Vector2(24, 0)))
	var drag_release := InputEventMouseButton.new()
	drag_release.button_index = MOUSE_BUTTON_LEFT
	drag_release.position = drag_motion.position
	game._input(drag_release)
	assert(not game.dragging, "active drags should receive release before the HUD")
	assert(not game.selection_drag_overlay.active and not game.selection_drag_overlay.tracking and not game.selection_drag_overlay.visible)
	var accumulated_before_drag := Input.use_accumulated_input
	var drag_press := InputEventMouseButton.new()
	drag_press.button_index = MOUSE_BUTTON_LEFT
	drag_press.pressed = true
	drag_press.position = Vector2(400, 300)
	game._unhandled_input(drag_press)
	assert(Input.use_accumulated_input == accumulated_before_drag, "clicking must not change the global input event mode")
	drag_release.position = drag_press.position
	game._input(drag_release)
	assert(Input.use_accumulated_input == accumulated_before_drag)
	game._unhandled_input(drag_press)
	game._set_paused(true)
	assert(Input.use_accumulated_input == accumulated_before_drag)
	assert(not game.selection_drag_overlay.visible)
	game._set_paused(false)
	assert(game._cursor_state_at(game.units[0].position) == "select")
	game._select_area(game.units[0].position, game.units[0].position, false)
	assert(game.info_label.text == "村民", "selection details should update immediately")
	game._select_area(Vector2(700, 700), Vector2(700, 700), false)
	assert(game.info_label.text == "未选择", "clearing selection should update details immediately")
	var center: RtsBuilding = game._player_center(0)
	game.selected.append(center)
	game._rebuild_actions()
	assert(game.command_buttons.size() >= 4, "Town Center should show villager training and garrison controls")
	assert(not game.command_buttons.any(func(button: RtsCommandButton) -> bool: return button.get_meta("action_type") in ["research", "landmark"]), "Town Center should not host military upgrades or age landmark choices")
	assert(game.hotkey_buttons.has(KEY_1))
	game.command_buttons[0].pressed.emit()
	assert(center.queued_unit_count("villager") == 1, "train command should enqueue a villager")
	var rally_destination: Vector2 = game._scaled_point(Vector2(800, 720))
	assert(game._cursor_state_at(rally_destination) == "rally")
	game._issue_order(rally_destination)
	assert(center.rally_point == rally_destination, "right click should set a producer's rally point")
	center._process(center._training_time("villager") + 1.0)
	var trained_villager: RtsUnit = game.units.back()
	assert(trained_villager.kind == "villager" and trained_villager.order == "move")
	assert(trained_villager.destination == rally_destination, "trained units should travel to the rally point")
	game.selected.clear()
	game.selected.append(trained_villager)
	game.build_page = 0
	game._rebuild_actions()
	var age_button: RtsCommandButton
	for button in game.command_buttons:
		if button.icon_kind == "age": age_button = button
	assert(age_button != null, "villagers should open the age landmark chooser")
	assert(age_button.text.is_empty() and age_button.tooltip_text.contains("选择地标并进入下一个时代"), "icon-only actions should explain their purpose on hover")
	age_button.pressed.emit()
	assert(game.age_choice_overlay != null, "age choices should open in a dedicated window")
	var council_choice: Button
	for button in game.age_choice_overlay.find_children("*", "Button", true, false):
		for label in button.find_children("*", "Label", true, false):
			if label.text.contains("议会厅"): council_choice = button
	assert(council_choice != null)
	var council_icon: TextureRect
	for image in council_choice.find_children("*", "TextureRect", true, false): council_icon = image
	assert(council_icon != null and council_icon.texture != null, "landmark choice should display its icon")
	assert(council_choice.find_children("*", "Label", true, false).any(func(label: Label) -> bool: return label.text.contains("训练时间减半")))
	assert(council_choice != null and not council_choice.disabled)
	council_choice.pressed.emit()
	assert(game.age_choice_overlay == null and game.build_mode == "landmark" and game.pending_landmark_id == "eng_council_hall")
	game.build_mode = ""
	game.pending_landmark_id = ""
	game.selected.clear()
	game.build_page = 0
	assert(is_equal_approx(game.minimap.size.x, game.minimap.size.y), "the minimap content should be square")
	var minimap_panel: PanelContainer = game.hud_ui.minimap_panel
	assert(is_equal_approx(minimap_panel.size.x, minimap_panel.size.y), "the minimap panel should keep a 1:1 footprint")
	var midpoint: Vector2 = game.minimap.map_to_world(game.minimap.size * 0.5)
	assert(midpoint.distance_to(game.world_size * 0.5) < 1.0)
	var map_click := InputEventMouseButton.new()
	map_click.button_index = MOUSE_BUTTON_LEFT
	map_click.pressed = true
	map_click.position = game.minimap.size * 0.5
	game.minimap._gui_input(map_click)
	assert(game.camera.position.distance_to(game.world_size * 0.5) < 1.0)
	var pan := InputEventPanGesture.new()
	pan.delta = Vector2(1.5, -2.0)
	var before_pan: Vector2 = game.camera.position
	game._unhandled_input(pan)
	assert(game.camera.position.is_equal_approx(before_pan + pan.delta * game.GESTURE_PAN_PIXELS), "trackpad pan should move the camera on both axes")
	game.camera.zoom = Vector2(1.25, 1.25)
	before_pan = game.camera.position
	game._unhandled_input(pan)
	assert(game.camera.position.is_equal_approx(before_pan + pan.delta * game.GESTURE_PAN_PIXELS / 1.25), "trackpad pan should account for zoom")
	pan.delta = Vector2(1000, 1000)
	game._unhandled_input(pan)
	assert(game.camera.position.is_equal_approx(game.world_size - game.get_viewport_rect().size * 0.5 / game.camera.zoom.x), "trackpad pan should stop at map edges")
	game._set_paused(true)
	before_pan = game.camera.position
	game._unhandled_input(pan)
	assert(game.camera.position == before_pan, "trackpad pan should stop while paused")
	game._set_paused(false)
	game.camera.zoom = Vector2.ONE
	game.camera.position = game.world_size * 0.5
	var worker: RtsUnit = game.units[0]
	var attempted_builders: Array[RtsUnit] = [worker]
	var wood_at_age_one: int = game.players[0]["wood"]
	assert(not game.place_building(0, "barracks", Vector2(570, 800), attempted_builders))
	assert(game.players[0]["wood"] == wood_at_age_one, "locked buildings should not charge resources")
	assert(game.advance_age(0))
	assert(game.players[0]["age"] == 1 and game.is_age_queued(0), "landmark construction should take time")
	var age_landmark: RtsBuilding = game.buildings.back()
	assert(age_landmark.kind == "landmark" and not age_landmark.is_complete())
	age_landmark.advance_construction(RtsTechTree.age_time(1))
	assert(game.players[0]["age"] == 2)
	assert(game.players[0]["landmarks"].has(age_landmark.landmark_id))
	var sample_archery: RtsBuilding = game.spawn_building(0, "archery_range", Vector2(700, 1040))
	assert(age_landmark.producer_kind() == "archery_range" and age_landmark._training_time("longbow") < sample_archery._training_time("longbow"), "Council Hall itself should train archery units faster")
	assert(RtsTechTree.buildable_buildings("English", 1) == ["house", "farm", "mill", "lumber_camp", "mining_camp"])
	assert(RtsTechTree.buildable_buildings("English", 2).has("barracks"))
	assert(RtsTechTree.trainable_units("English", 2, "archery_range") == ["longbow"])
	assert(RtsTechTree.trainable_units("French", 2, "archery_range") == ["archer"])
	assert(not RtsTechTree.can_train("English", 2, "barracks", "archer"))
	assert(not RtsTechTree.can_train("English", 1, "barracks", "spearman"))
	assert(not RtsTechTree.can_advance(4))
	game.selected.append(worker)
	game._rebuild_actions()
	assert(game.action_bar.columns == 4 and game.action_bar.get_child_count() == 12, "economy construction page should fill a 3×4 grid")
	assert(game.command_buttons[0].icon_kind == "house" and game.command_buttons[1].icon_kind == "lumber_camp" and game.command_buttons[4].icon_kind == "farm", "economy buildings should follow the reference order")
	assert(game.command_buttons[11].icon_kind == "wonder" and game.command_buttons[11].disabled and game.command_buttons[11].tooltip_text.contains("当前不可用"), "the wonder should remain visible with its age requirement")
	game.hud_ui.build_tab_bar.get_child(1).pressed.emit()
	assert(game.build_page == 1 and game.action_bar.get_child_count() == 12, "military construction page should fill a 3×4 grid")
	assert(game.command_buttons[0].icon_kind == "barracks" and game.command_buttons[3].icon_kind == "siege_workshop" and game.command_buttons[6].icon_kind == "palisade_wall" and game.command_buttons[9].icon_kind == "stone_gate", "military buildings should follow the reference order")
	game.hud_ui.build_tab_bar.get_child(0).pressed.emit()
	assert(game.build_page == 0)
	game.command_buttons[4].pressed.emit()
	assert(game.build_mode == "farm", "economy construction command should select a farm")
	game.build_mode = ""
	assert(game._cursor_state_at(game._player_center(1).position) == "move", "unseen enemies should not be targetable")
	assert(game._cursor_state_at(game.resources[0].position) == "gather")
	assert(game._cursor_state_at(Vector2(700, 700)) == "move")
	assert(game._cursor_state_at(Vector2(700, 700), true) == "default")
	var helper: RtsUnit = game.units[1]
	game.selected.append(helper)
	var wood_before: int = game.players[0]["wood"]
	game.build_mode = "barracks"
	game._confirm_build(Vector2(570, 800))
	assert(game.players[0]["wood"] == wood_before - 160, "building cost is paid once")
	game.build_mode = "house"
	assert(game._cursor_state_at(Vector2(570, 800)) == "build_invalid")
	assert(game._cursor_state_at(Vector2(700, 800)) == "build_valid")
	game.build_mode = ""
	var barracks: RtsBuilding = game.buildings.back()
	assert(worker.order == "build" and helper.order == "build")
	assert(game.count_builders(barracks) == 2)
	worker.position = barracks.position + Vector2(50, 0)
	helper.position = barracks.position + Vector2(-50, 0)
	worker._process(1.0)
	helper._process(1.0)
	assert(is_equal_approx(barracks.build_remaining, barracks.build_total - 2.0), "two builders should double construction progress")
	worker.order_move(Vector2(700, 800))
	helper.order_move(Vector2(700, 800))
	var saved_progress: float = barracks.build_remaining
	assert(game.count_builders(barracks) == 0)
	game._issue_order(barracks.position)
	assert(worker.order == "build" and helper.order == "build", "right click should resume construction")
	assert(game._cursor_state_at(barracks.position) == "construct")
	assert(is_equal_approx(barracks.build_remaining, saved_progress), "interruption should preserve progress")
	worker._process(1.0)
	helper._process(1.0)
	assert(is_equal_approx(barracks.build_remaining, saved_progress - 2.0))
	barracks.advance_construction(100.0)
	assert(barracks.is_complete())
	game.selected.clear()
	game.selected.append(barracks)
	game._rebuild_actions()
	assert(game.action_bar.columns == 4 and game.command_buttons[0].icon_kind == "spearman" and game.command_buttons[1].icon_kind == "man_at_arms", "barracks should place units in the icon grid")
	assert(not game.train_unit(barracks, "archer"), "a producer cannot train another building's units")
	assert(game.train_unit(barracks, "spearman"))
	barracks._process(GameData.training_time("English", "barracks", "spearman"))
	var spearman: RtsUnit = game.units.back()
	assert(spearman.kind == "spearman")
	game.selected.clear()
	game.selected.append(spearman)
	game._rebuild_actions()
	assert(game.command_buttons.size() >= 2, "military units should show attack-move and stop")
	var command_scroll: ScrollContainer = game.action_bar.get_parent()
	assert(command_scroll.vertical_scroll_mode == ScrollContainer.SCROLL_MODE_DISABLED and command_scroll.horizontal_scroll_mode == ScrollContainer.SCROLL_MODE_DISABLED, "the command panel must not show scroll bars")
	assert(game.command_buttons.size() > 12 and game.command_buttons.filter(func(button: RtsCommandButton) -> bool: return button.visible).size() == 12, "long command lists should show one 3×4 page at a time")
	game.hud_ui.build_tab_bar.get_child(1).pressed.emit()
	assert(game.command_buttons.back().icon_kind == "stop" and game.command_buttons.back().visible, "the second command page should keep later orders accessible")
	game.hud_ui.build_tab_bar.get_child(0).pressed.emit()
	game.command_buttons[0].pressed.emit()
	assert(game.order_mode == "attack_move" and game._cursor_state_at(Vector2(700, 700)) == "attack_move")
	game._issue_attack_move(Vector2(900, 700))
	assert(spearman.order == "attack_move" and game.order_mode == "")
	game.hotkey_buttons[KEY_2].pressed.emit()
	assert(spearman.order == "idle", "stop should clear a unit order")
	spearman.issue_command("move", Vector2(800, 900))
	var first_destination: Vector2 = spearman.destination
	spearman.issue_command("move", Vector2(880, 900), null, true)
	assert(spearman.command_queue.size() == 1 and spearman.destination == first_destination, "Shift should append without replacing the active order")
	spearman.position = first_destination
	spearman._process(0.0)
	assert(spearman.command_queue.is_empty() and spearman.order == "move" and spearman.destination != first_destination, "queued movement should start when the first move completes")
	spearman.order_stop()
	assert(spearman.command_queue.is_empty(), "stop should clear queued commands")
	var base_damage: float = spearman.stats["damage"]
	game.credit_resource(0, "food", 200)
	game.credit_resource(0, "gold", 100)
	assert(game.research_technology(barracks, "forged_weapons"))
	assert(game.queued_research(0).has("forged_weapons"))
	barracks._process(RtsTechTree.TECHNOLOGIES["forged_weapons"]["time"])
	assert(game.players[0]["researched"].has("forged_weapons"))
	assert(spearman.stats["damage"] == base_damage + 2.0, "research should update existing units")
	var food_before_cancel: int = game.players[0]["food"]
	assert(game.train_unit(barracks, "spearman"))
	assert(game.cancel_production_job(barracks, 0))
	assert(game.players[0]["food"] == food_before_cancel, "canceled production should refund its cost")
	var depleted_wood: RtsResource = game.spawn_resource("wood", game._scaled_point(Vector2(1080, 750)), 1)
	var rally_wood: RtsResource = game.spawn_resource("wood", game._scaled_point(Vector2(745, 930)), 90)
	center.set_rally(rally_wood.position, rally_wood)
	assert(game.train_unit(center, "villager"))
	center._process(center._training_time("villager") + 1.0)
	var rally_villager: RtsUnit = game.units.back()
	assert(rally_villager.order == "gather" and rally_villager.target == rally_wood, "resource rally should send new villagers straight to gathering")
	game.spawn_resource("gold", game._scaled_point(Vector2(1115, 750)), 10)
	var nearby_wood: RtsResource = game.spawn_resource("wood", game._scaled_point(Vector2(1155, 750)), 1)
	worker.position = depleted_wood.position + Vector2(20, 0)
	helper.position = depleted_wood.position + Vector2(-20, 0)
	game.fog.update_visibility()
	worker.work_timer = 0.0
	helper.work_timer = 0.0
	worker.order_gather(depleted_wood)
	helper.order_gather(depleted_wood)
	worker._process(1.1)
	assert(worker.order == "gather" and worker.target is RtsResource and worker.target.kind == "wood" and worker.target != depleted_wood and worker.target.position.distance_to(depleted_wood.position) <= RtsUnit.AUTO_GATHER_RADIUS, "a worker should continue to nearby wood when a node is depleted")
	helper._process(1.1)
	assert(helper.order == "gather" and helper.target is RtsResource and helper.target.kind == "wood" and helper.target != depleted_wood and helper.target.position.distance_to(depleted_wood.position) <= RtsUnit.AUTO_GATHER_RADIUS, "other workers should also leave a depleted node")
	worker.position = nearby_wood.position + Vector2(20, 0)
	worker._process(1.1)
	assert(worker.order == "idle" or worker.target is RtsResource and worker.target.kind == "wood" and worker.target.position.distance_to(nearby_wood.position) <= RtsUnit.AUTO_GATHER_RADIUS, "a worker should only continue to nearby resources of the same kind")
	var outpost: RtsBuilding = game.spawn_building(0, "outpost", game._scaled_point(Vector2(760, 680)))
	assert(outpost.garrison_unit(spearman), "outposts should accept infantry garrisons")
	assert(spearman.garrisoned_in == outpost and not spearman.visible)
	var enemy_probe: RtsUnit = game.spawn_unit(1, "spearman", outpost.position + Vector2(115, 0))
	enemy_probe.revealed_timer = 3.0
	game.fog.update_visibility()
	outpost._process(2.0)
	assert(outpost.defense_timer > 0.0, "a completed outpost should fire at a nearby enemy")
	outpost.ungarrison_all()
	assert(spearman.garrisoned_in == null and spearman.visible)
	game.entity_destroyed(enemy_probe)
	var enemy_wall: RtsBuilding = game.spawn_building(1, "stone_wall", game._scaled_point(Vector2(1050, 680)))
	var ram: RtsUnit = game.spawn_unit(0, "battering_ram", game._scaled_point(Vector2(975, 680)))
	ram.position = enemy_wall.position - Vector2(75, 0)
	ram.order_attack(enemy_wall)
	var wall_hp: float = enemy_wall.hp
	ram._process(0.0)
	assert(enemy_wall.hp < wall_hp - 50.0, "a ram should deliver structure bonus damage in the live combat path")
	game.start_game("French")
	var unfinished_ai_building: RtsBuilding = game.spawn_building(1, "house", game._scaled_point(Vector2(1750, 850)), true)
	assert(game.count_builders(unfinished_ai_building) == 0)
	game.ai.tick()
	assert(game.count_builders(unfinished_ai_building) > 0, "AI should resume an abandoned building")
	assert(game.civilizations[0] == "French")
	assert(not RtsTechTree.can_train("French", 2, "archery_range", "longbow"))
	assert(RtsTechTree.can_train("French", 2, "stable", "royal_knight"))
	assert(GameData.gathered_amount("English", "food", true) > GameData.gathered_amount("French", "food", true))
	assert(GameData.training_time("French", "stable", "royal_knight") < RtsBalanceData.training_seconds("royal_knight"))
	var ai_landmark: RtsBuilding
	for building in game.buildings:
		if building.owner_id == 1 and building.kind == "landmark": ai_landmark = building
	assert(ai_landmark != null)
	ai_landmark.advance_construction(RtsTechTree.age_time(1))
	assert(game.players[1]["age"] == 2, "AI should advance to age 2")
	game._player_center(1).take_damage(2000)
	assert(not game.game_over, "a surviving landmark should prevent elimination")
	ai_landmark.take_damage(3000)
	assert(game.game_over, "destroying the opposing Town Center and landmark should end the match")
	print("SMOKE_OK")
	quit()
