extends SceneTree

func _initialize() -> void:
	call_deferred("_run")

func _run() -> void:
	var scene := load("res://scenes/main.tscn")
	var game: Variant = scene.instantiate()
	root.add_child(game)
	await process_frame
	game.start_game("English", 12345)
	assert(game.map_seed == 12345)
	var terrain_map: RtsWorldMap = game.world_map
	assert(terrain_map.cells.has(RtsWorldMap.Terrain.WATER), "map should contain water")
	assert(terrain_map.cells.has(RtsWorldMap.Terrain.MOUNTAIN), "map should contain mountains")
	assert(terrain_map.plants.size() > 100, "map should contain plant groups")
	var deer_count := 0
	for spec in terrain_map.resource_specs:
		if spec["appearance"] == "deer": deer_count += 1
	assert(deer_count >= 12, "map should contain harvestable deer herds")
	var same_seed_map := RtsWorldMap.new()
	same_seed_map.generate(12345, game.world_size)
	assert(same_seed_map.cells == terrain_map.cells and same_seed_map.resource_specs == terrain_map.resource_specs, "map generation should be reproducible")
	same_seed_map.free()
	var corridor := terrain_map.path_between(Vector2(330, 720), Vector2(2070, 720))
	assert(not corridor.is_empty(), "both bases should be connected")
	for waypoint in corridor: assert(terrain_map.is_walkable(waypoint))
	var water_point := Vector2(800, 1220)
	assert(not terrain_map.is_walkable(water_point))
	assert(not game.can_place("house", water_point), "water should block construction")
	assert(game.weather.rain_active, "a new map should start with rain")
	game.weather.weather_remaining = 0.01
	game.weather._process(0.02)
	assert(not game.weather.rain_active, "rain should give way to clear weather")
	assert(game.units.size() == 10, "both civilizations should have starting villagers")
	assert(game.buildings.size() == 2, "both civilizations should have town centers")
	assert(game.population_cap(0) == 10)
	var escape := InputEventKey.new()
	escape.keycode = KEY_ESCAPE
	escape.pressed = true
	game._input(escape)
	assert(game.paused and game.pause_overlay.visible)
	assert(Input.mouse_mode == Input.MOUSE_MODE_VISIBLE)
	assert(not game.cursor.visible)
	var frozen_position: Vector2 = game.units[0].position
	game.units[0]._process(1.0)
	assert(game.units[0].position == frozen_position)
	game._input(escape)
	assert(not game.paused and not game.pause_overlay.visible)
	assert(game.cursor.visible)
	assert(game._edge_pan_direction(Vector2(640, 360), Vector2(1280, 720)) == Vector2.ZERO)
	assert(game._edge_pan_direction(Vector2(2, 360), Vector2(1280, 720)) == Vector2.LEFT)
	assert(game._edge_pan_direction(Vector2(1278, 718), Vector2(1280, 720)) == Vector2(1, 1))
	assert(game._edge_pan_direction(Vector2(-2, 360), Vector2(1280, 720)) == Vector2.ZERO)
	assert(game._cursor_state_at(game.units[0].position) == "select")
	game._select_area(game.units[0].position, game.units[0].position, false)
	assert(game.info_label.text == "村民", "selection details should update immediately")
	game._select_area(Vector2(700, 700), Vector2(700, 700), false)
	assert(game.info_label.text == "未选择", "clearing selection should update details immediately")
	var center: RtsBuilding = game._player_center(0)
	game.selected.append(center)
	game._rebuild_actions()
	assert(game.command_buttons.size() == 4, "Town Center should show training, future research, and age-up commands")
	assert(game.command_buttons[1].disabled and game.command_buttons[1].availability_reason.contains("时代"), "locked research should explain its requirement")
	assert(game.hotkey_buttons.has(KEY_1))
	game.command_buttons[0].pressed.emit()
	assert(center.training_queue.size() == 1, "train command should enqueue a villager")
	var rally_destination := Vector2(800, 720)
	assert(game._cursor_state_at(rally_destination) == "rally")
	game._issue_order(rally_destination)
	assert(center.rally_point == rally_destination, "right click should set a producer's rally point")
	center._process(10.0)
	var trained_villager: RtsUnit = game.units.back()
	assert(trained_villager.kind == "villager" and trained_villager.order == "move")
	assert(trained_villager.destination == rally_destination, "trained units should travel to the rally point")
	game.selected.clear()
	var midpoint: Vector2 = game.minimap.map_to_world(game.minimap.size * 0.5)
	assert(midpoint.distance_to(game.world_size * 0.5) < 1.0)
	var map_click := InputEventMouseButton.new()
	map_click.button_index = MOUSE_BUTTON_LEFT
	map_click.pressed = true
	map_click.position = game.minimap.size * 0.5
	game.minimap._gui_input(map_click)
	assert(game.camera.position.distance_to(game.world_size * 0.5) < 1.0)
	var pan := InputEventPanGesture.new()
	pan.delta = Vector2(1.5, -2.0)
	var before_pan: Vector2 = game.camera.position
	game._unhandled_input(pan)
	assert(game.camera.position.is_equal_approx(before_pan + pan.delta * game.GESTURE_PAN_PIXELS), "trackpad pan should move the camera on both axes")
	game.camera.zoom = Vector2(1.25, 1.25)
	before_pan = game.camera.position
	game._unhandled_input(pan)
	assert(game.camera.position.is_equal_approx(before_pan + pan.delta * game.GESTURE_PAN_PIXELS / 1.25), "trackpad pan should account for zoom")
	pan.delta = Vector2(1000, 1000)
	game._unhandled_input(pan)
	assert(game.camera.position.is_equal_approx(game.world_size - game.get_viewport_rect().size * 0.5 / game.camera.zoom.x), "trackpad pan should stop at map edges")
	game._set_paused(true)
	before_pan = game.camera.position
	game._unhandled_input(pan)
	assert(game.camera.position == before_pan, "trackpad pan should stop while paused")
	game._set_paused(false)
	game.camera.zoom = Vector2.ONE
	game.camera.position = game.world_size * 0.5
	var worker: RtsUnit = game.units[0]
	var attempted_builders: Array[RtsUnit] = [worker]
	var wood_at_age_one: int = game.players[0]["wood"]
	assert(not game.place_building(0, "barracks", Vector2(570, 800), attempted_builders))
	assert(game.players[0]["wood"] == wood_at_age_one, "locked buildings should not charge resources")
	assert(game.advance_age(0))
	assert(game.players[0]["age"] == 1 and game.is_age_queued(0), "age advancement should take production time")
	center._process(RtsTechTree.age_time(1))
	assert(game.players[0]["age"] == 2)
	assert(RtsTechTree.buildable_buildings("English", 1) == ["house", "farm"])
	assert(RtsTechTree.buildable_buildings("English", 2).has("barracks"))
	assert(RtsTechTree.trainable_units("English", 2, "archery_range") == ["longbow"])
	assert(RtsTechTree.trainable_units("French", 2, "archery_range") == ["archer"])
	assert(not RtsTechTree.can_train("English", 2, "barracks", "archer"))
	assert(not RtsTechTree.can_train("English", 1, "barracks", "spearman"))
	assert(not RtsTechTree.can_advance(4))
	game.selected.append(worker)
	game._rebuild_actions()
	assert(game.command_buttons.size() == 6, "villager should see all construction commands and stop")
	game.command_buttons[1].pressed.emit()
	assert(game.build_mode == "farm", "second construction command should select a farm")
	game.build_mode = ""
	assert(game._cursor_state_at(game._player_center(1).position) == "attack")
	assert(game._cursor_state_at(game.resources[0].position) == "gather")
	assert(game._cursor_state_at(Vector2(700, 700)) == "move")
	assert(game._cursor_state_at(Vector2(700, 700), true) == "default")
	var helper: RtsUnit = game.units[1]
	game.selected.append(helper)
	var wood_before: int = game.players[0]["wood"]
	game.build_mode = "barracks"
	game._confirm_build(Vector2(570, 800))
	assert(game.players[0]["wood"] == wood_before - 160, "building cost is paid once")
	game.build_mode = "house"
	assert(game._cursor_state_at(Vector2(570, 800)) == "build_invalid")
	assert(game._cursor_state_at(Vector2(700, 800)) == "build_valid")
	game.build_mode = ""
	var barracks: RtsBuilding = game.buildings.back()
	assert(worker.order == "build" and helper.order == "build")
	assert(game.count_builders(barracks) == 2)
	worker.position = barracks.position + Vector2(50, 0)
	helper.position = barracks.position + Vector2(-50, 0)
	worker._process(1.0)
	helper._process(1.0)
	assert(is_equal_approx(barracks.build_remaining, barracks.build_total - 2.0), "two builders should double construction progress")
	worker.order_move(Vector2(700, 800))
	helper.order_move(Vector2(700, 800))
	var saved_progress: float = barracks.build_remaining
	assert(game.count_builders(barracks) == 0)
	game._issue_order(barracks.position)
	assert(worker.order == "build" and helper.order == "build", "right click should resume construction")
	assert(game._cursor_state_at(barracks.position) == "construct")
	assert(is_equal_approx(barracks.build_remaining, saved_progress), "interruption should preserve progress")
	worker._process(1.0)
	helper._process(1.0)
	assert(is_equal_approx(barracks.build_remaining, saved_progress - 2.0))
	barracks.advance_construction(100.0)
	assert(barracks.is_complete())
	assert(not game.train_unit(barracks, "archer"), "a producer cannot train another building's units")
	assert(game.train_unit(barracks, "spearman"))
	barracks._process(GameData.training_time("English", "barracks", "spearman"))
	var spearman: RtsUnit = game.units.back()
	assert(spearman.kind == "spearman")
	game.selected.clear()
	game.selected.append(spearman)
	game._rebuild_actions()
	assert(game.command_buttons.size() == 2, "military units should show attack-move and stop")
	game.command_buttons[0].pressed.emit()
	assert(game.order_mode == "attack_move" and game._cursor_state_at(Vector2(700, 700)) == "attack_move")
	game._issue_attack_move(Vector2(900, 700))
	assert(spearman.order == "attack_move" and game.order_mode == "")
	game.command_buttons[1].pressed.emit()
	assert(spearman.order == "idle", "stop should clear a unit order")
	var base_damage: float = spearman.stats["damage"]
	game.credit_resource(0, "food", 200)
	game.credit_resource(0, "gold", 100)
	assert(game.research_technology(barracks, "forged_weapons"))
	assert(game.queued_research(0).has("forged_weapons"))
	barracks._process(RtsTechTree.TECHNOLOGIES["forged_weapons"]["time"])
	assert(game.players[0]["researched"].has("forged_weapons"))
	assert(spearman.stats["damage"] == base_damage + 2.0, "research should update existing units")
	var food_before_cancel: int = game.players[0]["food"]
	assert(game.train_unit(barracks, "spearman"))
	assert(game.cancel_production_job(barracks, 0))
	assert(game.players[0]["food"] == food_before_cancel, "canceled production should refund its cost")
	var depleted_wood: RtsResource = game.spawn_resource("wood", Vector2(900, 850), 1)
	game.spawn_resource("gold", Vector2(935, 850), 10)
	var nearby_wood: RtsResource = game.spawn_resource("wood", Vector2(975, 850), 1)
	worker.position = depleted_wood.position + Vector2(20, 0)
	helper.position = depleted_wood.position + Vector2(-20, 0)
	worker.work_timer = 0.0
	helper.work_timer = 0.0
	worker.order_gather(depleted_wood)
	helper.order_gather(depleted_wood)
	worker._process(1.1)
	assert(worker.order == "gather" and worker.target == nearby_wood, "a worker should continue to nearby wood when a node is depleted")
	helper._process(1.1)
	assert(helper.order == "gather" and helper.target == nearby_wood, "other workers should also leave a depleted node")
	worker.position = nearby_wood.position + Vector2(20, 0)
	worker._process(1.1)
	assert(worker.order == "idle" or worker.target is RtsResource and worker.target.kind == "wood" and worker.target.position.distance_to(nearby_wood.position) <= RtsUnit.AUTO_GATHER_RADIUS, "a worker should only continue to nearby resources of the same kind")
	game.start_game("French")
	var unfinished_ai_building: RtsBuilding = game.spawn_building(1, "house", Vector2(1750, 850), true)
	assert(game.count_builders(unfinished_ai_building) == 0)
	game.ai.tick()
	assert(game.count_builders(unfinished_ai_building) > 0, "AI should resume an abandoned building")
	assert(game.civilizations[0] == "French")
	assert(not RtsTechTree.can_train("French", 2, "archery_range", "longbow"))
	assert(RtsTechTree.can_train("French", 2, "stable", "royal_knight"))
	assert(GameData.gathered_amount("English", "food", true) > GameData.gathered_amount("French", "food", true))
	assert(GameData.training_time("French", "stable", "royal_knight") < GameData.UNITS["royal_knight"]["time"])
	game._player_center(1)._process(RtsTechTree.age_time(1))
	assert(game.players[1]["age"] == 2, "AI should advance to age 2")
	game._player_center(1).take_damage(2000)
	assert(game.game_over, "destroying the opposing Town Center should end the match")
	print("SMOKE_OK")
	quit()
